### ISSUE TITLE
Can't Activate Till 5.5+

### ISSUE THREAD

**Issue by heyfletch** [whyisjake/disable-plugin-theme-auto-updates#3]
Does this need to be minimum version 5.5? I can't activate it on 5.4. I'd like to activate it before 5.5. lands so that there is no risk of auto-updates occurring if I upgrade to 5.5. before activating this plugin.

**Comment by whyisjake** [comment]
Great point, I'll update.

**Comment by heyfletch** [comment]
Awesome, thanks!  🎉
